on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create and populate app.rsa file
        env:
          AWS_HOST: ${{ secrets.LT_USERNAME }}          
        run: |
          
          cd ..
          cd ..
          touch app.rsa
          ls -la
          cd .github/workflows
          echo "$AWS_HOST" >> "./app.rsa"
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"